/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ChatImport } from './routes/chat'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as ChatSettingsImport } from './routes/chat.settings'
import { Route as ChatCreateChatImport } from './routes/chat.create-chat'
import { Route as ChatChatIdImport } from './routes/chat.$chatId'
import { Route as ChatChatIdDetailsImport } from './routes/chat.$chatId.details'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatSettingsRoute = ChatSettingsImport.update({
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)

const ChatCreateChatRoute = ChatCreateChatImport.update({
  path: '/create-chat',
  getParentRoute: () => ChatRoute,
} as any)

const ChatChatIdRoute = ChatChatIdImport.update({
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)

const ChatChatIdDetailsRoute = ChatChatIdDetailsImport.update({
  path: '/details',
  getParentRoute: () => ChatChatIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdImport
      parentRoute: typeof ChatImport
    }
    '/chat/create-chat': {
      id: '/chat/create-chat'
      path: '/create-chat'
      fullPath: '/chat/create-chat'
      preLoaderRoute: typeof ChatCreateChatImport
      parentRoute: typeof ChatImport
    }
    '/chat/settings': {
      id: '/chat/settings'
      path: '/settings'
      fullPath: '/chat/settings'
      preLoaderRoute: typeof ChatSettingsImport
      parentRoute: typeof ChatImport
    }
    '/chat/$chatId/details': {
      id: '/chat/$chatId/details'
      path: '/details'
      fullPath: '/chat/$chatId/details'
      preLoaderRoute: typeof ChatChatIdDetailsImport
      parentRoute: typeof ChatChatIdImport
    }
  }
}

// Create and export the route tree

interface ChatChatIdRouteChildren {
  ChatChatIdDetailsRoute: typeof ChatChatIdDetailsRoute
}

const ChatChatIdRouteChildren: ChatChatIdRouteChildren = {
  ChatChatIdDetailsRoute: ChatChatIdDetailsRoute,
}

const ChatChatIdRouteWithChildren = ChatChatIdRoute._addFileChildren(
  ChatChatIdRouteChildren,
)

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRouteWithChildren
  ChatCreateChatRoute: typeof ChatCreateChatRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRouteWithChildren,
  ChatCreateChatRoute: ChatCreateChatRoute,
  ChatSettingsRoute: ChatSettingsRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chat': typeof ChatRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/create-chat': typeof ChatCreateChatRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/chat/$chatId/details': typeof ChatChatIdDetailsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chat': typeof ChatRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/create-chat': typeof ChatCreateChatRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/chat/$chatId/details': typeof ChatChatIdDetailsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chat': typeof ChatRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/chat/create-chat': typeof ChatCreateChatRoute
  '/chat/settings': typeof ChatSettingsRoute
  '/chat/$chatId/details': typeof ChatChatIdDetailsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/chat'
    | '/login'
    | '/register'
    | '/chat/$chatId'
    | '/chat/create-chat'
    | '/chat/settings'
    | '/chat/$chatId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/chat'
    | '/login'
    | '/register'
    | '/chat/$chatId'
    | '/chat/create-chat'
    | '/chat/settings'
    | '/chat/$chatId/details'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/chat'
    | '/login'
    | '/register'
    | '/chat/$chatId'
    | '/chat/create-chat'
    | '/chat/settings'
    | '/chat/$chatId/details'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChatRoute: typeof ChatRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChatRoute: ChatRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/chat",
        "/login",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.jsx"
    },
    "/chat": {
      "filePath": "chat.tsx",
      "children": [
        "/chat/$chatId",
        "/chat/create-chat",
        "/chat/settings"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/chat/$chatId": {
      "filePath": "chat.$chatId.tsx",
      "parent": "/chat",
      "children": [
        "/chat/$chatId/details"
      ]
    },
    "/chat/create-chat": {
      "filePath": "chat.create-chat.tsx",
      "parent": "/chat"
    },
    "/chat/settings": {
      "filePath": "chat.settings.tsx",
      "parent": "/chat"
    },
    "/chat/$chatId/details": {
      "filePath": "chat.$chatId.details.tsx",
      "parent": "/chat/$chatId"
    }
  }
}
ROUTE_MANIFEST_END */
